[build]
builder = "dockerfile"

[deploy]
startCommand = "node dist/app.js"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production"
PORT = "3001"
